Issue and PR-Template
OpenEnergyPlatform/open-MaStR pull request #428
Opened 2023-02-08 13:52 UTC by steull

closes #427

2023-02-08 15:00 UTC, FlorianK13 commented
@steull Thanks for these templates. Could you change the target branch to develop? Then we will merge it to production within the next Release.

2023-02-09 15:04 UTC, FlorianK13 commented
Just saw that I can also change the base branch

2023-02-09 16:47 UTC, jh-RLI commented
Hey, I asked @steull  if he rolls out the templates in all open energy family repos. We are currently developing them internally at RLI. I think it will not change much more. So feel free to merge and use them already. This is also a small part of my master thesis, so feel free to give feedback on whether you are comfortable using the template structure :)

2023-02-09 16:49 UTC, jh-RLI commented
I just noticed that they include a link to an external repository. You might want to update the link to the contributing.md of the open_MaStR repo. :)

2023-02-10 12:40 UTC, chrwm requested changes
Thanks for the initiative.
Please fix the requested changes and I'll approve. THX!

2023-02-10 12:40 UTC, chrwm commented on .github/ISSUE_TEMPLATE/issue_template_bug.md
> +- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)
```suggestion
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
```

2023-02-10 12:40 UTC, chrwm commented on .github/ISSUE_TEMPLATE/issue_template_feature.md
> +- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)
```suggestion
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
```

2023-02-10 12:40 UTC, chrwm commented on .github/pull_request_template.md
> +- Add a new class [(#)](https://github.com/rl-institut/super-repo/pull/)
```suggestion
- Add a new class [(#)](https://github.com/OpenEnergyPlatform/open-MaStR/pull/)
```

2023-02-10 12:40 UTC, chrwm commented on .github/pull_request_template.md
> +- Update a definition [(#)](https://github.com/rl-institut/super-repo/pull/)
```suggestion
- Update a definition [(#)](https://github.com/OpenEnergyPlatform/open-MaStR/pull/)
```

2023-02-10 12:40 UTC, chrwm commented on .github/pull_request_template.md
> +- Remove a broken link [(#)](https://github.com/rl-institut/super-repo/pull/)
```suggestion
- Remove a broken link [(#)](https://github.com/OpenEnergyPlatform/open-MaStR/pull/)
```

2023-02-10 12:40 UTC, chrwm commented on .github/pull_request_template.md
> +- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)
```suggestion
- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
```

2023-02-10 12:40 UTC, chrwm commented on .github/pull_request_template.md
> +- [ ] 📝 Update the [CHANGELOG.md](https://github.com/rl-institut/super-repo/blob/develop/CHANGELOG.md)
```suggestion
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CHANGELOG.md)
```

2023-02-10 12:40 UTC, chrwm commented on .github/pull_request_template.md
> +- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
@steull please add the "Reviewer Guidlines" to this repo & update the link or delete the line

2023-02-15 08:41 UTC, chrwm approved these changes
@steull, I incorporated the changes.
Please merge today or tomorrow, before 11 a.m.. THX!

2023-02-15 08:41 UTC, chrwm commented on .github/pull_request_template.md
> +- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
```suggestion
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
```

2023-02-16 12:04 UTC, merged