Develop
OpenEnergyPlatform/open-MaStR pull request #471
Opened 2023-10-11 12:04 UTC by Grazvy

## Summary of the discussion

Describe the findings of the discussion in the issue or meeting.

## Type of change (CHANGELOG.md)

### Added
- New method in mastr.py to translate the columns of the connected database
- Dictionary of translations in constants.py
- Methods in helpers.py for translating and connecting to a translated database
- Tests for new functionality

### Updated
- Mastr class parameters to allow connections to translated databases

### Removed

## Workflow checklist

### Automation
Closes #

### PR-Assignee
- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CHANGELOG.md)
- [ ] 📙 Update the documentation

### Reviewer
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

2023-10-18 15:04 UTC, FlorianK13 requested changes
Thanks for your PR @Grazvy I have added a few comments, we can also discuss them further.

2023-10-18 15:04 UTC, FlorianK13 commented on environment.yml
> +name: py39_open_mastr
Here it could be updated to py310_open_mastr, to use the same version as in the pre-commit config file

2023-10-18 15:04 UTC, FlorianK13 commented on .pre-commit-config.yaml
> +        language_version: python3.8
Can you revert this commit? We need to stay at python3.10

2023-10-18 15:04 UTC, FlorianK13 commented on open_mastr/mastr.py
> +            "yyyymmdd". Defaults to None.
We would still need the string = "existing" in the docstring

2023-10-18 15:04 UTC, FlorianK13 commented on open_mastr/mastr.py
> +
Did you delete this on purpose? If so, did you make sure it is not used by any other function? It seems like this gives the possibility to use an environment variable as the output_dir

2023-10-18 15:04 UTC, FlorianK13 commented on open_mastr/mastr.py
> +        if self.is_translated:
Maybe it would be useful to have this at the very beginning, to stop the download function before other stuff is triggered?

2023-10-18 15:04 UTC, FlorianK13 commented on open_mastr/utils/helpers.py
> +        if date != "today":
Here we still need the existing parameter

2023-10-18 15:04 UTC, FlorianK13 commented on open_mastr/utils/helpers.py
> -        if date == "existing":
Here also we still need the existing stuff. Did you merge develop from open_mastr into develop at Grazvy?

2023-10-19 14:58 UTC, Grazvy commented on open_mastr/mastr.py
> +
No it was not on purpose, I think it was based on the production version of mastr.py which did not use get_output_dir() or the "existing" parameter. I will adjust it based on the development version.

2023-11-02 07:58 UTC, FlorianK13 approved these changes

2023-11-02 08:24 UTC, FlorianK13 commented
Github secrets are not communicated to external PRs, hence the API tests cannot run successfully. I propose we merge it anyway and see if the tests run when we want to merge to production?

2023-11-02 15:56 UTC, FlorianK13 commented
The tests for this branch are also failing locally, I will investigate why this is the case before we merge.

2023-11-03 09:18 UTC, FlorianK13 commented
Tests suceeded locally, hence I will merge it now

2023-11-03 09:19 UTC, merged