Feature 489 requests identify as open mastr
OpenEnergyPlatform/open-MaStR pull request #519
Opened 2024-05-16 09:50 UTC by FlorianK13

### Automation
Closes #489 

### PR-Assignee
- [ ] 🐙 Follow the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md)
- [ ] 📝 Update the [CHANGELOG.md](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CHANGELOG.md)
- [ ] 📙 Update the documentation

### Reviewer
- [ ] 🐙 Follow the [Reviewer Guidelines](https://github.com/OpenEnergyPlatform/open-MaStR/blob/production/CONTRIBUTING.md#40-let-someone-else-review-your-pr)
- [ ] 🐙 Provided feedback and show sufficient appreciation for the work done

2024-05-17 15:26 UTC, chrwm requested changes
From what I understood, HEADERS is a constant that is not changed by the programme code. If so, I suggest to capitalise it for better readability and maintainability.

2024-05-17 15:26 UTC, chrwm commented on open_mastr/xml_download/utils_download_bulk.py
> +    headers = {"User-Agent": "python-package-open-mastr"}
```suggestion
    HEADERS= {"User-Agent": "python-package-open-mastr"}
```

2024-05-17 15:26 UTC, chrwm commented on open_mastr/xml_download/utils_download_bulk.py
> +    r = requests.get(url, stream=True, headers=headers)
```suggestion
    r = requests.get(url, stream=True, headers=HEADERS)
```

2024-05-17 15:26 UTC, chrwm commented on open_mastr/xml_download/utils_download_bulk.py
> +        r = requests.get(url, stream=True, headers=headers)
```suggestion
        r = requests.get(url, stream=True, headers=HEADERS)
```

2024-05-24 09:37 UTC, chrwm approved these changes, later dismissed
Thanks for the implementation!

2024-05-24 11:00 UTC, chrwm approved these changes

2024-05-28 07:34 UTC, FlorianK13 commented
This is paused, as a better solution exists in #526

2024-05-28 08:21 UTC, closed without merging